let vegetables=["Tomato","Potato","Brinjal"];
console.log(vegetables);
vegetables.push("Ladyfinger");
console.log(vegetables);
vegetables.pop();
console.log(vegetables);
vegetables.shift();
console.log(vegetables);
vegetables.shift();
console.log(vegetables);
vegetables.unshift("Capsicum");
console.log(vegetables);